### ISSUE TITLE
Why include a header file from the src directory in the header file which exposed to the outside in the include directory?

### ISSUE THREAD

**Issue by nolongerwait** [volcengine/ve-tos-cpp-sdk#24] opened 2023-03-10 02:06 UTC
If I compile this repository into a library and provide it for my program to use (not compiling together with the complete source code), will your code be able to pass compilation? 

The header file under the exposed Include directory refers to a header file that cannot be found after the compilation into the library.

https://github.com/volcengine/ve-tos-cpp-sdk/blob/12a0a00910fc9599b96a88fd1aa2b3975f1e5c2b/sdk/include/model/acl/DeleteBucketCORSOutput.h#L3

**Comment by zihaoyue2022** [comment] 2023-03-10 08:45
This is a problem caused by an incorrect script, which has been fixed in version 2.5.5

**Closed** 2023-03-11 09:38 UTC
